ValueSet: VsMinisteroSaluteIdAziendeOspedaliere
Id: minsan-idAziendeOspedaliere
Title: "Ministero della Salute - ID Aziende Ospedaliere"
Description: "Ministero della Salute - Aziende Ospedaliere (HSP11)"
* ^experimental = false
//----------------------------------------
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#010906 "AZ. OSPEDAL. S. CROCE E CARLE"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#010907 "AZ. SS.ANTONIO E BIAGIO E C.ARRIGO"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#010908 "OSPEDALE MAURIZIANO UMBERTO I - TORINO"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030701 "ASST GRANDE OSPEDALE METROPOLITANO NIGUA"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030702 "ASST SANTI PAOLO E CARLO"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030703 "ASST FATEBENEFRATELLI SACCO"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030704 "ASST SPEC.ORT.TRAUMATOLOGICO G.PINI/CTO"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030705 "ASST OVEST MILANESE"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030706 "ASST RHODENSE"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030707 "ASST NORD MILANO"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030708 "ASST MELEGNANO E DELLA MARTESANA"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030709 "ASST DI LODI"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030710 "ASST DEI SETTE LAGHI"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030711 "ASST DELLA VALLE OLONA"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030712 "ASST LARIANA"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030713 "ASST DELLA VALTELLINA E DELL'ALTO LARIO"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030714 "ASST DELLA VALCAMONICA"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030715 "ASST DI LECCO"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030717 "ASST DELLA BRIANZA"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030718 "ASST PAPA GIOVANNI XXIII"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030719 "ASST DI BERGAMO OVEST"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030720 "ASST DI BERGAMO EST"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030721 "ASST DEGLI SPEDALI CIVILI DI BRESCIA"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030722 "ASST DELLA FRANCIACORTA"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030723 "ASST DEL GARDA"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030724 "ASST DI CREMONA"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030725 "ASST DI MANTOVA"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030726 "ASST DI CREMA"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030727 "ASST DI PAVIA"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#050901 "AZIENDA OSPEDALE - UNIVERSITA' PADOVA"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#100901 "AZIENDA OSPEDALIERA DI PERUGIA"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#100902 "AZIENDA OSPEDALIERA 'S. MARIA' - TERNI"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#110905 "AZIENDA OSP. UNIVERSITARIA DELLE MARCHE"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#120901 "AZ.OSP.SAN CAMILLO-FORLANINI"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#120902 "AZIENDA OSP. S.GIOVANNI/ADDOLORATA ROMA"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#150901 "AZIENDA OSPEDALIERA 'A. CARDARELLI'"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#150902 "A.O.R.N. SANTOBONO-PAUSILIPON"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#150903 "Azienda Ospedaliera dei Colli"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#150905 "AZIENDA OSPEDALIERA S. G. MOSCATI"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#150906 "AZIENDA OSPEDALE `AO SAN PIO"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#150907 "A.O. SANT'ANNA E SAN SEBASTIANO CASERTA"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#170901 "AZIENDA OSPEDALIERA REGIONALE 'S. CARLO'"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#180912 "AZIENDA OSPEDALIERA DI COSENZA"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#180913 "Azienda Ospedaliera Pugliese - Ciaccio"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#180914 "A.O.U. MATER DOMINI CATANZARO"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#180915 "Azienda Osped. Bianchi Melacrino Morelli"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#190921 "A.O. per l'Emergenza Cannizzaro"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#190922 "ARNAS GARIBALDI"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#190924 "Azienda Ospedaliera Papardo"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#190926 "A.O.R Villa Sofia Cervello"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#190927 "Azienda Ospedaliera 'Civico-Di Cristina-"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#200904 "AZIENDA OSPEDALIERA G.BROTZU"


ValueSet: VsMinisteroSaluteIdStruttureInterne
Id: minsan-idStruttureInterne
Title: "Ministero della Salute - ID Strutture Interne di Ricovero"
Description: "Ministero della Salute - Identificativi Strutture Interne di Ricovero"
//-------------------------------------------------------------------------------------------
* ^experimental = false
* ^status = #active

* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#010030.01 "OSPEDALE CIVILE E.AGNELLI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#010030.03 "OSPEDALE DI POMARETTO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#010079.01 "OSPEDALE DEGLI INFERMI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#010079.02 "OSPEDALE CIVILE DI GIAVENO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#010079.04 "OSPEDALE CIVILE DI SUSA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#010079.05 "OSPEDALE DI VENARIA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#010079.06 "UNITA' AUTONOMA DI DAY SURGERY DI AVIGLI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#010019.01 "PRESIDIO OSPED. RIUNITO SEDE DI CIRIE'"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#010019.03 "PRESIDIO OSPED. RIUNITO SEDE DI LANZO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#010023.01 "OSPEDALE CIVILE DI IVREA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#010023.02 "OSPEDALE CIVILE DI CUORGNE'"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#010023.04 "SAAPA S.P.A."
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#010004.01 "OSPEDALE MAGGIORE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#010004.02 "OSPEDALE SANTA CROCE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#010004.03 "OSPEDALE SAN LORENZO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#010004.04 "DAY SURGERY DEL DISTRETTO DI NICHELINO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#010009.01 "OSPEDALE SANT'ANDREA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#010009.02 "OSPEDALE SS.PIETRO E PAOLO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#010005.01 "OSPEDALE SAN BIAGIO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#010005.02 "STABILIMENTO OSPEDALIERO CASTELLI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#010005.03 "C.O.Q. OSPEDALE MADONNA DEL POPOLO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#010124.01 "OSPEDALE DI MONDOVI' CN1"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#010124.02 "NUOVO OSPEDALE DI CEVA CN1"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#010126.01 "OSP. MAGGIORE SS. ANNUNZIATA SAVIGLIANO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#010126.02 "OSP. CIVILE DI SALUZZO CN1"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#010120.01 "OSPEDALE SAN LAZZARO - ALBA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#010120.02 "OSPEDALE SANTO SPIRITO BRA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#010008.01 "PRESIDIO OSP. CARDINAL G. MASSAIA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#010008.02 "PRESIDIO OSPEDALIERO S. SPIRITO-VALLE BE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#010026.01 "OSPEDALE SANTO SPIRITO CASALE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#010026.03 "OSPEDALE SS. ANTONIO E MARGHERITA TORTON"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#010026.04 "OSPEDALE SAN GIACOMO NOVI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#010026.05 "OSPEDALE CIVILE ACQUI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#010026.06 "OSPEDALE CIVILE OVADA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#010905.01 "OSP. MAGGIORE DELLA CARITA'"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#010905.02 "OSPEDALE SAN ROCCO GALLIATE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#010907.01 "OSP.CIVILE SS.ANTONIO E BIAGIO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#010907.02 "OSP. INFANTILE C.ARRIGO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#010907.03 "CENTRO RIABILITATIVO POLIFUNZIONALE T.BO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#010909.01 "OSPEDALE SAN GIOVANNI BATTISTA MOLINETTE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#010909.02 "OSPEDALE DERMATOLOGICO SAN LAZZARO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#010909.04 "OSPEDALE CENTRO TRAUMATOLOGICO ORTOPEDIC"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#010909.05 "ISTITUTO CHIRURGICO ORTOPEDICO REGINA MA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#010909.06 "OSPEDALE OSTETRICO GINECOLOGICO SANT'ANN"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#010909.07 "OSPEDALE INFANTANTILE REGINA MARGHERITA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#030281.01 "OSPEDALE DI LEGNANO E CUGGIONO-LEGNANO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#030281.02 "OSPEDALE DI LEGNANO E CUGGIONO-LEGNANO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#030071.01 "OSPEDALE S. MARIA DELLE STELLE MELZO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#030071.02 "OSPEDALE S. MARIA DELLE STELLE MELZO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#030072.01 "OSPEDALE DI  VIZZOLO PREDABISSI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#030072.02 "OSPEDALE DI  VIZZOLO PREDABISSI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#030085.01 "OSPEDALE UBOLDO - CERNUSCO S/NAVIGLIO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#030085.02 "OSPEDALE UBOLDO - CERNUSCO S/NAVIGLIO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#030282.01 "PRESIDIO OSPEDALIERO DEL VERBANO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#030282.02 "PRESIDIO OSPEDALIERO DEL VERBANO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#030901.01 "PRESIDIO OSPEDALIERO DI VARESE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#030901.02 "PRESIDIO OSPEDALIERO DI VARESE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#030901.03 "PRESIDIO OSPEDALIERO DI VARESE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#030274.01 "OSPEDALE VALCAMONICA - ESINE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#030274.02 "OSPEDALE VALCAMONICA - ESINE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#030154.01 "PRESIDIO OSPEDALIERO DI CHIARI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#030154.02 "PRESIDIO OSPEDALIERO DI CHIARI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#030227.01 "PRESIDIO OSPEDALIERO - ASOLA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#030227.02 "PRESIDIO OSPEDALIERO - ASOLA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#030936.01 "IST.AUXOLOGICO ITALIANO-I.S. S.LUCA-MILA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#030936.02 "IST.AUXOLOGICO ITAL.-I.S. S.MICHELE-MILA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#030936.03 "IRCCS OSPEDALE CAPITANIO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#042001.01 "PRESIDIO OSPEDALIERO S. CHIARA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#042001.03 "PRESIDIO OSPEDALIERO VILLA ROSA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#042001.04 "PRESIDIO OSPEDALIERO VILLA IGEA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050201.01 "OSPEDALE S. MARTINO BELLUNO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050201.03 "OSPEDALE DI AGORDO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050201.04 "OSPEDALE DI PIEVE DI CADORE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050202.01 "OSPEDALE DI FELTRE 'S. MARIA DEL PRATO'"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050202.02 "OSPEDALE DI LAMON 'CASA CHARITAS'"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050203.01 "OSPEDALE `SAN BASSIANO` DI BASSANO D.G."
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050203.02 "OSPEDALE DI ASIAGO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050205.01 "OSPEDALE DI ARZIGNANO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050205.02 "OSPEDALE  DI LONIGO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050205.03 "OSPEDALE DI MONTECCHIO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050205.04 "OSPEDALE DI VALDAGNO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050206.01 "PRES. OSPED. VICENZA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050206.02 "PRES. OSP.  NOVENTA VICENTINA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050140.01 "ASSOCIAZIONE LA NS. FAMIGLIA IRCSS MEDEA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050140.02 "ASSOCIAZIONE LA NS.FAMIGLIA IRCSS MEDEA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050207.01 "OSPEDALE DI CONEGLIANO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050207.02 "OSPEDALE DI VITTORIO VENETO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050208.01 "OSPEDALE DI CASTELFRANCO VENETO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050208.02 "OSPEDALE DI MONTEBELLUNA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050209.01 "OSPEDALE CA' FONCELLO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050209.02 "OSPEDALE DI ODERZO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050210.01 "PRESIDIO OSPEDALIERO DI PORTOGRUARO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050210.02 "PRESIDIO OSPEDALIERO DI SAN DONA` DI P."
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050210.03 "PRESIDIO OSPEDALIERO DI JESOLO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050212.01 "OSPEDALE CIVILE VENEZIA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050212.02 "PUNTO PRIMO INTERVENTO LIDO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050212.04 "OSPEDALE DELL'ANGELO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050213.01 "OSPEDALE  DI DOLO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050213.02 "OSPEDALE  DI MIRANO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050213.03 "OSPEDALE DI NOALE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050215.01 "PRESIDIO OSPEDALIERO DI CAMPOSAMPIERO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050215.02 "PRESIDIO OSPEDALIERO DI CITTADELLA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050216.01 "OSPEDALE SANT`ANTONIO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050216.05 "OSP. IMMACOL. CONCEZ. DI PIOVE DI SACCO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050217.03 "SEDE MONTAGNANA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050217.04 "SEDE CONSELVE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050217.05 "OSPEDALI RIUNITI PADOVA SUD"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050218.01 "P.O. DI ROVIGO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050218.02 "P.O. DI TRECENTA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050220.04 "PRESIDIO OSP. MARZANA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050220.05 "POLO OSP. DELL'EST VERONESE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050220.06 "PSICHIATRIA SEZIONE B.GO TRENTO - VERONA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050221.01 "OSPEDALE PER ACUTI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050221.03 "OSPEDALE S.BIAGIO BOVOLONE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050222.01 "OSPEDALE CIVILE ORLANDI BUSSOLENGO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050222.02 "OSPEDALE ISOLA DELLA SCALA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050222.04 "OSPEDALE DI MALCESINE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050222.05 "OSPEDALE MAGALINI - VILLAFRANCA DI VR"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050912.01 "OSPEDALE CIVILE MAGGIORE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#050912.02 "OSPEDALE POLICLINICO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#060043.01 "PO Gorizia e Monfalcone sede Gorizia"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#060043.02 "PO Gorizia e Monfalcone sede Monfalcone"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#060044.01 "PO Latisana e Palmanova sede Latisana"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#060044.02 "PO Latisana e Palmanova sede Palmanova"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#060045.01 "Sede di San Daniele"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#060045.02 "Sede di Tolmezzo"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#060045.03 "Sede di Gemona"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#060047.01 "PRESIDIO OSPEDALIERO SMM - SEDE UDINE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#060047.02 "PRESIDIO OSPEDAL. SMM - SEDE CIVIDALE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#060042.01 "P.O. San Vito al T. sede di S. Vito al T"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#060042.02 "P.O. San Vito al T. sede di Spilimbergo"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#070001.01 "STABILIMENTO OSPEDALIERO DI IMPERIA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#070001.02 "STABILIMENTO OSPEDALIERO DI SANREMO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#070001.03 "STABILIMENTO OSPEDALIERO DI BORDIGHERA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#070211.01 "OSPEDALE SANTA MARIA MISERICORDIA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#070211.02 "OSPEDALE SANTA CORONA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#070212.03 "OSPEDALE SAN GIUSEPPE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#070212.04 "OSPEDALE SAN PAOLO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#070051.01 "EVANGELICO Internazionale CASTELLETTO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#070051.02 "EVANGELICO-SAN CARLO VOLTRI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#070301.01 "OSPEDALE LA COLLETTA ARENZANO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#070301.03 "OSPEDALE PADRE ANTERO MICONE SESTRI P."
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#070301.04 "OSPEDALE VILLA SCASSI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#070301.05 "OSPEDALE GALLINO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#070039.01 "OSP. RIUNITI LEONARDI E RIBOLI LAVAGNA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#070039.02 "OSPEDALE CIVILE DI SESTRI LEVANTE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#070039.05 "OSPEDALE N.S. DI MONTALLEGRO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#070058.01 "OSPEDALE SANT`ANDREA LA SPEZIA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#070058.03 "OSPEDALE SAN NICOLO` LEVANTO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#070058.04 "STABILIMENTO SAN BARTOLOMEO DI SARZANA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#080004.01 "OSPEDALE GUGLIELMO DA SALICETO PIACENZA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#080004.02 "OSPEDALE BOBBIO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#080004.03 "OSPEDALE CASTEL SAN GIOVANNI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#080004.04 "OSPEDALE BORGONOVO VAL TIDONE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#080004.05 "OSPEDALE FIORENZUOLA D'ARDA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#080004.06 "CENTRO DI RECUPERO E RIABILITAZIONE FUNZ"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#080013.01 "OSPEDALE FIDENZA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#080013.03 "OSPEDALE 'S.MARIA' BORGO VAL DI TARO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#080021.01 "OSPEDALE CIVILE GUASTALLA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#080021.02 "OSPEDALE S.SEBASTIANO CORREGGIO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#080021.03 "OSPEDALE E.FRANCHINI MONTECCHIO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#080021.04 "OSPEDALE G.MAGATI SCANDIANO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#080021.05 "OSPEDALE S.ANNA CASTELNOVO NE MONTI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#080031.04 "OSPEDALE B. RAMAZZINI  CARPI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#080031.05 "OSPEDALE SANTA MARIA BIANCA  MIRANDOLA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#080031.08 "OSPEDALE VIGNOLA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#080031.09 "OSPEDALE PAVULLO NEL FRIGNANO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#080031.10 "NUOVO OSPEDALE CIVILE  S.AGOSTINO - ESTE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#080053.01 "OSPEDALE MAGGIORE C.A. PIZZARDI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#080053.02 "OSPEDALE BELLARIA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#080053.03 "OSPEDALE DOSSETTI  BAZZANO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#080053.04 "OSPEDALE A. COSTA PORRETTA TERME (ALTO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#080053.05 "OSPEDALE VERGATO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#080053.06 "OSPEDALE SIMIANI LOIANO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#080053.07 "OSPEDALE BENTIVOGLIO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#080053.08 "OSPEDALE BUDRIO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#080053.09 "OSPEDALE S.SALVATORE  S. GIOVANNI IN P"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#080044.01 "OSPEDALE CIVILE NUOVO S.MARIA DELLA SCA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#080044.02 "OSPEDALE CASTEL SAN PIETRO TERME"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#080068.03 "OSPEDALE DEL DELTA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#080068.04 "OSPEDALE MAZZOLANI VANDINI ARGENTA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#080068.06 "STABILIMENTO OSPEDALIERO SS. ANNUNZIATA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#080085.01 "OSPEDALE MORGAGNI-PIERANTONI FORLI'"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#080085.03 "OSPEDALE NEFETTI SANTA SOFIA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#080091.01 "OSPEDALE MAURIZIO BUFALINI CESENA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#080091.02 "OSPEDALE GINESIO MARCONI CESENATICO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#080091.03 "OSPEDALE PIETRO ANGIOLONI BAGNO DI ROM"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#080095.01 "OSPEDALE INFERMI RIMINI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#080095.02 "OSPEDALE FRANCHINI SANTARCANGELO DI RO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#080095.03 "OSPEDALE SACRA FAMIGLIA NOVAFELTRIA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#080100.01 "OSPEDALE CECCARINI RICCIONE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#080100.02 "OSPEDALE CERVESI CATTOLICA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#080903.01 "AZIENDA OSPEDALIERA DI REGGIO EMILIA-S."
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#080903.02 "AZIENDA OSPEDALIERA DI REGGIO EMILIA - I"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#090606.01 "OSPEDALE SAN JACOPO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#090606.02 "OSPEDALE LORENZO PACINI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#090629.01 "OSPEDALE S.M.ANNUNZIATA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#090629.02 "OSPEDALE SERRISTORI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#090632.01 "SANTA MARIA NUOVA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#090632.02 "ISTITUTO ORTOPEDICO TOSCANO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#090632.03 "OSP. S. GIOVANNI DI DIO TORREGALLI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#090632.06 "OBLATE AZIENDA SANITARIA FIRENZE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#090642.02 "OSPEDALE S. GIUSEPPE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#090642.03 "OSPEDALE SAN PIETRO IGNEO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#090642.04 "OSPEDALE DEGLI INFERMI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#090601.01 "OSP. S. ANTONIO ABATE FIVIZZANO   (MS)"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#090601.02 "OSP. CIV. S.ANTONIO  PONTREMOLI (MS)"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#090602.01 "STABILIMENTO OSPEDALIERO DI CARRARA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#090602.03 "OSPEDALE  DELLE APUANE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#090603.01 "OSPEDALE SANTA CROCE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#090603.02 "OSPEDALE SAN FRANCESCO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#090610.01 "P.O. F. LOTTI STABILIMENTO DI PONTEDERA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#090610.02 "SPDC AZIENDALE ASL5"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#090236.01 "CASA DI CURA POGGIO DEL SOLE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#090236.02 "CENTRO CHIRURGICO TOSCANO SRL"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#090624.02 "OSPEDALE DI ORBETELLO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#090624.03 "OSPEDALE DI PITIGLIANO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#090907.01 "FONDAZIONE CNR-RT G. MONASTERIO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#090907.02 "OSPEDALE DEL CUORE G. PASQUINUCCI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#100801.01 "OSPEDALE DI CITTA` DI CASTELLO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#100801.02 "OSPEDALE DI UMBERTIDE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#100803.01 "STAB.OSPEDALIERO CASTIGLIONE DEL LAGO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#100803.02 "STAB.OSPEDALIERO CITTA`DELLA PIEVE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#100803.03 "C.O.R.I. - PASSIGNANO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#100803.04 "STAB. OSPEDALIERO ASSISI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#100803.07 "STAB. OSPEDALIERO MEDIA VALLE DEL TEVERE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#100805.01 "OSPEDALE CIVILE SAN MATTEO DEGLI INFERMI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#100805.02 "OSPEDALE CIVILE DI NORCIA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#100805.03 "OSPEDALE S.RITA CASCIA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#100807.01 "STABILIMENTO OSPEDALIERO DI NARNI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#100807.02 "STABILIMENTO OSPEDALIERO DI AMELIA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#100807.03 "DOMUS GRATIAE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#100809.01 "OSPEDALE SAN GIOVANNI BATTISTA FOLIGNO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#100809.02 "STABILIMENTO DI TREVI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#110001.01 "OSP S. MARIA DELLA MISERICORDIA - URBINO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#110001.02 "OSPEDALE SS DONNINO E CARLO - PERGOLA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#110001.03 "OSPEDALE CELLI - CAGLI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#110001.04 "OSPEDALE LANCIARINI - SASSOCORVARO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#110001.05 "OSPEDALE CIVILE - FOSSOMBRONE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#110002.01 "PRESIDIO OSPEDALIERO ZT 4 - SENIGALLIA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#110002.02 "OSPEDALE CARLO URBANI DI JESI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#110002.03 "OSP. SS. BENVENUTO E ROCCO - OSIMO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#110002.04 "OSPEDALE CIVILE 'E.PROFILI' - FABRIANO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#110002.05 "OSPEDALE SANTA CASA - LORETO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#110002.06 "OSPEDALE GENERALE DI ZONA - CINGOLI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#110003.01 "OSPEDALE GENERALE DI ZONA - CIVITANOVA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#110003.02 "OSPEDALE GENERALE PROVINCIALE - MACERATA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#110003.03 "OSPEDALE S.MARIA DELLA PIETA` - CAMERINO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#110003.04 "OSPEDALE B.EUSTACCHIO - S. SEVERINO M."
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#110003.05 "OSPEDALE DI TREIA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#110003.06 "OSPEDALE DI TOLENTINO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#110003.07 "OSPEDALE CIVILE SANTA LUCIA - RECANATI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#110003.08 "OSPEDALE S.SOLLECITO - MATELICA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#110004.01 "OSPEDALE DI FERMO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#110004.02 "OSPEDALE VITTORIO EMANUELE II - AMANDOLA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#110005.01 "MADONNA DEL SOCCORSO - S.BENEDETTO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#110005.02 "OSP. GEN."
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#110901.01 "OSPEDALE SAN SALVATORE - PESARO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#110901.02 "OSPEDALE SANTA CROCE - FANO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#110905.01 "PRESIDIO OSPEDALIERO UMBERTO I°"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#110905.02 "PRESIDIO OSPEDALIERO G.M.LANCISI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#110905.03 "PRESIDIO OSPEDALIERO G.SALESI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#110921.01 "OSPEDALE INRCA - ANCONA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#110921.02 "OSPEDALE INRCA - FERMO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#120204.01 "ALFREDO FIORINI TERRACINA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#120204.02 "SAN GIOVANNI DI DIO FONDI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#120204.03 "REGINA ELENA PRIVERNO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#120026.01 "OSPEDALE SANTO SPIRITO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#120026.02 "VILLA BETANIA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#120285.01 "PRESIDIO SAN FILIPPO NERI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#120285.03 "PRESIDIO CASSIA SANT'ANDREA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#120285.05 "SALUS INFIRMORUM"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#120066.01 "OSPEDALE S.EUGENIO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#120066.02 "OSPEDALE CTO.A.ALESINI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#120044.01 "OSPEDALE SAN GIUSEPPE ALBANO L."
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#120044.02 "OSPEDALE E. DE SANTIS GENZANO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#120904.01 "OSPEDALE PEDIATRICO BAMBINO GESU`"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#120904.02 "OSPEDALE PEDIATRICO BAMBINO GESU`"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#120904.03 "OSPEDALE PEDIATRICO BAMBINO GESU`"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#120905.01 "POLICLINICO UNIVERSITARIO A. GEMELLI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#120905.02 "COMPLESSO INTEGRATO COLUMBUS (C.I.C.)"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#120908.01 "IFO - ISTITUTO REGINA ELENA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#120908.02 "IFO - ISTITUTO SAN GALLICANO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#140002.01 "OSPEDALE S. TIMOTEO- TERMOLI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#140002.02 "OSPEDALE G. VIETRI- LARINO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#140003.01 "OSPEDALE VENEZIALE- ISERNIA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#140003.02 "OSPEDALE CARACCIOLO AGNONE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#140003.03 "OSPEDALE SS. ROSARIO - VENAFRO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#150150.01 "OSPEDALE S.ANGELO DEI LOMBARDI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#150150.02 "P.SP.RIABILITATIVO DON GNOCCHI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#150418.01 "PO SAN GIOVANNI BOSCO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#150418.02 "PO LORETO MARE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#150418.05 "PO ASCALESI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#150418.06 "PRESDIO SANITARIO INTERMEDIO NAPOLI EST"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#150419.01 "PO SAN PAOLO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#150419.02 "PO DEI PELLEGRINI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#150419.03 "PO SAN GENNARO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#150419.04 "PO SMDP INCURABILI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#150419.06 "PO  Capilupi CAPRI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#150415.01 "P.O. MARESCA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#150415.02 "P.O.  BOSCOTRECASE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#150416.01 "S.  LEONARDO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#150416.02 "NUOVO GRAGNANO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#150417.01 "P.O. S. MARIA DELLA MISERICORDIA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#150417.02 "P.O. DE LUCA E ROSSANO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#150436.01 "OSPEDALI RIUNITI AREA NOLANA PLESSO NOLA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#150436.02 "OSPED RIUNITI AREA NOLANA PLESSO POLLENA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#150154.01 "P.O. UMBERTO I NOCERA INFERIORE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#150154.02 "P.O. TORTORA PAGANI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#150902.01 "OSPEDALE SANTOBONO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#150902.02 "Ospedale Pausilipon"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#150902.03 "P.O. S.S. Annunziata"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#150903.01 "Azienda Ospedaliera dei Colli -P Monaldi"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#150903.02 "Azienda Ospedaliera dei Colli -P Cotugno"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#150903.03 "Azienda Ospedaliera dei Colli -P  CTO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#150904.01 "A.O. OO.RR. SANGIOVANNI DI DIO E RUGGI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#150904.02 "OSPEDALE AMICO G. FUCITO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#150904.03 "P.O. G. DA PROCIDA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#150904.04 "P.O. S. M. DELL'OLMO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#160161.01 "OSPEDALE OSTUNI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#160161.02 "PLESSO DI FASANO - OSPEDALE OSTUNI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#160170.01 "OSPEDALE PERRINO BRINDISI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#160170.02 "OSPEDALE BRINDISI (PLESSO MESAGNE)"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#160170.03 "OSP.BRINDISI(PLESSO S.PIETRO VERNOTICO)"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#160170.04 "OSP.BRINDISI (PLESSO CEGLIE MESSAPICA)"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#160172.01 "OSPEDALE SS ANNUNZIATA - TARANTO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#160172.03 "OSPEDALE MOSCATI - TARANTO/STATTE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#160174.01 "OSPEDALE ANDRIA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#160174.02 "OSPEDALE ANDRIA (PLESSO CANOSA)"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#160178.01 "OSPEDALE BISCEGLIE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#160178.02 "OSPEDALE BISCEGLIE (PLESSO TRANI)"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#160158.01 "OSPEDALE SAN PAOLO-BARI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#160158.03 "OSPEDALE SAN PAOLO (PLESSO MOLFETTA)"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#160158.04 "OSPEDALE SAN PAOLO (PLESSO CORATO)"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#160158.05 "OSPEDALE SAN PAOLO (PLESSO TERLIZZI)"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#160169.01 "OSPEDALE DI VENERE - BARI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#160169.03 "PLESSO TRIGGIANO-OSPEDALE DI VENERE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#160163.01 "OSPEDALE SAN SEVERO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#160163.07 "OSPEDALE SAN SEVERO (PLESSO LUCERA)"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#160171.01 "OSPEDALE LECCE 'V FAZZI'"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#160171.02 "PLESSO DI SAN CESARIO - OSPEDALE LECCE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#160907.01 "CONSORZIALE POLICLINICO BARI"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#160907.02 "OSPEDALE GIOVANNI XXIII"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#170901.01 "Ospedale San Carlo di Potenza"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#170901.02 "Osp S.Francesco di Paola di Pescopagano"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#180010.01 "Ospedale Corigliano"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#180010.02 "Ospedale  Rossano"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#180012.01 "Ospedale  Cetraro"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#180012.02 "Ospedale Paola"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#180912.01 "P.O. ANNUNZIATA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#180912.02 "MARIANO SANTO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#180912.03 "SANTA BARBARA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#180913.01 "Ospedale Pugliese"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#180913.02 "Ospedale De Lellis"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#180915.01 "Presidio Ospedaliero Riuniti"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#180915.02 "Presidio Ospedaliero E. Morelli"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#190922.01 "OSPEDALE GARIBALDI - CENTRO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#190922.04 "NUOVO OSPEDALE GARIBALDI - NESIMA"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#190923.01 "PRESIDIO OSPEDALIERO GASPARE RODOLICO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#190923.02 "PRESIDIO OSPEDALIERO VITTORIO EMANUELE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#190923.03 "PRESIDIO OSPEDALIERO S. BAMBINO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#190926.01 "P.O. Villa Sofia"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#190926.02 "C.T.O. Centro Traumatologico Ortopedico"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#190926.03 "P.O. V. Cervello"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#190927.01 "Ospedale Civico"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#190927.02 "Ospedale dei Bambini G. Di Cristina"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#190960.01 "IRCCS Centro Neurolesi"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#190960.02 "PRESIDIO OSPEDALIERO PIEMONTE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#200056.01 "KINETIKA SARDEGNA s.r.l."
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#200056.02 "KINETIKA SARDEGNA s.r.l."
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#200056.03 "KINETIKA SARDEGNA s.r.l."
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#200904.01 "P. O. SAN MICHELE"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#200904.02 "P.O. A. BUSINCO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#200904.03 "P.O. MICROCITEMICO"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#200905.01 "Stabilimento Cliniche di San Pietro"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#200905.02 "Stabilimento SS. Annunziata"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#200906.01 "San Giovanni di Dio"
* http://hl7.it/fhir/televisita/CodeSystem/cs-mds-idStruttureInterne#200906.02 "Policlinico Monserrato"
